### ISSUE TITLE
Data availability

### ISSUE THREAD

**Issue by mcleanm** [SMLC-NYSBC/TARGET-VAE#1]
Hi there,
I noticed that the `data` directory is empty. Are the preprocessed EMPIAR-10025 (and/or MNIST, galaxy zoo, etc.) datasets used for training available online?
Best,
Michael

**Comment by alireza-nasiri** [comment]
Hi,
You can download mnist(N) and mnist(U) under datasets in the readme page of the repo. The EMPIAR-10025 can be downloaded from https://www.ebi.ac.uk/empiar/EMPIAR-10025/, and dSprites from https://github.com/deepmind/dsprites-dataset. 
Some other datasets can be found here: https://github.com/tbepler/spatial-VAE.
Best,
Ali
